### PR TITLE
Add RAPIDS and XGBoost logos

### PR DESCRIPTION
**Pull request by mrocklin**
I also rearrange some of the logos a bit to align similar projects (The scikits, xarray/iris, ML packages, ...)

### CODE REVIEW

**Comment by mrocklin** [comment]
Screen Shot 2019-05-29 at 8 56 39 AM

**Comment by TomAugspurger** [comment]
nitpick: you included periods in the descriptions, the others don't.

It looks like all the descriptions are full sentences, so personally I would prefer all the descriptions end with one.

**Comment by mrocklin** [comment]
> It looks like all the descriptions are full sentences

I think that many of the descriptions are technically noun phrases :) They lack verbs.

> A community effort for big data geoscience in the cloud

We should standardize though.  Maybe

> Short description of project

> Brief detail on how they use Dask

**Comment by jakirkham** [comment]
@TomAugspurger @mrocklin, what is the next step here?

**Comment by TomAugspurger** [comment]
IMO, just removing some periods for now :)

**Comment by mrocklin** [comment]
I think I've removed all added periods.  I'm not sure if this is what
you're looking for Tom. I'm not sure how best to handle this.

**Comment by TomAugspurger** [comment]
Yep, you got what I wanted: now all the descriptions are consistent (no trailing period). We can change that later if we wish.

Thanks!

**Comment by jakirkham** [comment]
Thanks all! 😄

**Pull request merged**
