### PR TITLE
Add link to ML slides

### PR DESCRIPTION
**Pull request by TomAugspurger**
cc @jrbourbeau @mrocklin

### CODE REVIEW

**Review by jrbourbeau — APPROVED** [review]
Thanks @TomAugspurger, this LGTM. Just as a heads up, I was having some permissions issues with the demos:

Screen Shot 2019-11-04 at 9 15 09 AM

**Comment by TomAugspurger** [comment]
Thanks. I made the videos public so it should be visible now.

If we want, I can upload them to our youtube account.

**Comment by mrocklin** [comment]
Awesome slide deck and videos @TomAugspurger !  I enjoyed going through them.  Some comments:

1.  Yes please upload them.  They would be great to add to the channel
2.  Would it be possible to add your voice to them?  
3.  I've stopped using `client.persist` in favor of `dask.persist`
4.  Do we know what's stopping RandomForest and HyperBand from getting good utilization?  You have some notes for RandomForest, but this seems like the sort of thing that someone might take on as a benchmark/profiling task if we pose the question well enough for them.

**Comment by TomAugspurger** [comment]
Thanks. I think my source had audio, and I lost it when running through
ffmpeg. I'll take a look.

I also noticed those inefficiencies. Haven't tracked them down yet, but
looking into it.

**Pull request merged**
