### PR TITLE
Add DataPrep

### LINKED ISSUE #31: Adding DataPrep to "Powered by Dask"
Hi team, our new library, DataPrep (https://github.com/sfu-db/dataprep), is using Dask for its execution engine. Is there any chance that we can be listed under the "Powered by Dask" section on "https://dask.org/"?

DataPrep is a library that lets data scientists prepare the data using a single library with a few lines of code. One of its modules, DataPrep.eda uses Dask extensively as its execution engine for calculating the statistics and data for charts.

### PR DESCRIPTION
**Pull request by dovahcrow**
Add DataPrep to the home page. DataPrep is a python library for data preparation. One of its modules, EDA, uses dask extensively as the execution engine.

This resolves #31.

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
Thanks for the PR @dovahcrow. There's now an empty spot after Karthotek in the grid of projects (screenshot below). Could you please move the downstream projects up to fill in the gap? 

Screen Shot 2020-08-24 at 11 44 46 AM

**Comment by dovahcrow** [comment]
@jrbourbeau Oh sorry I forgot the format. It is fixed!

**Review by jrbourbeau — APPROVED** [review]
Thanks @dovahcrow!

**Comment by dovahcrow** [comment]
Thanks @jrbourbeau  for your help!

**Pull request merged**
