### PR TITLE
Update copyright year

### PR DESCRIPTION
**Pull request by jrbourbeau**
2018 -> 2019

### CODE REVIEW

**Comment by mrocklin** [comment]
Thanks @jrbourbeau !

**Comment by martindurant** [comment]
I thought this was not legally necessary, copyright means "since". Don't sue me :)

**Comment by jrbourbeau** [comment]
Whoops, I definitely misunderstood that then. I can make a PR reverting back to 2018

**Comment by martindurant** [comment]
I think it's fine, leave it - this is true too

On May 14, 2019 9:07:56 PM EDT, James Bourbeau <notifications@github.com> wrote:
>Whoops, I definitely misunderstood that then. I can make a PR reverting
>back to 2018 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/dask/dask.github.io/pull/5#issuecomment-492465737

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
