### PR TITLE
Add "Powered by Dask" section

### PR DESCRIPTION
**Pull request by jrbourbeau**
This PR adds a new page to dask.org to highlight companies, institutions, and other software projects that use Dask. Related to https://github.com/dask/dask/issues/1496. 

For the time being, I'm re-using the logos from the "Supported By" section in place of company logos. Not sure if we need some kind of permission before using company logos.

I plan to iterate based on feedback from others. Pushing commits directly to this PR is also welcome.

### CODE REVIEW

**Comment by mrocklin** [comment]
This looks like a great start.  Thanks for putting this together @jrbourbeau !

My two first reactions are ...
1.  More logos :)  In particular for software projects this should be easy to obtain (though requires a bit of legwork to hunt down nice images)  My sense is that throwing a large number of logos at the user when they first see the page will leave a nice impression.
2.  Align descriptions with the logos, perhaps side by side like the following:

```
XXXXXXXX              XXXXXXXX              XXXXXXXXX
X      X  Text about  X      X  Text about  X       X  Text about
X      X  the project X      X  the project X       X  thee project
XXXXXXXX              XXXXXXXX              XXXXXXXXX

XXXXXXXX              XXXXXXXX              XXXXXXXXX
X      X  Text about  X      X  Text about  X       X  Text about
X      X  the project X      X  the project X       X  thee project
XXXXXXXX              XXXXXXXX              XXXXXXXXX

XXXXXXXX              XXXXXXXX              XXXXXXXXX
X      X  Text about  X      X  Text about  X       X  Text about
X      X  the project X      X  the project X       X  thee project
XXXXXXXX              XXXXXXXX              XXXXXXXXX
```

(though of course this is a non-trivial amount of work)

**Comment by mrocklin** [comment]
For the software projects I'm curious if we can use a company logo in describing who makes that project.  I'm curious if this falls under "fair use".  We're not explicitly using the company logo to endorse our project.  We're using the logo to talk about who made a particular piece of software.


```
XXXXXXXXXXXXXXX
X RAPIDS LOGO X
XXXXXXXXXXXXXXX

made by 

XXXXXXXXXXXXXXX
X NVIDIA LOGO X
XXXXXXXXXXXXXXX
```

To be clear I'm not saying "we should do this" I'm saying, "we should probably look into this"

**Comment by datametrician** [comment]
I believe you'd have to ask for permission, but I doubt many companies would push back.

**Comment by mrocklin** [comment]
We don't have to get their permission if this falls under fair use.  It may be that it's fair use to use a logo to provide information about who maintains a software project.  For example, my understanding is that if I write a blogpost about RAPIDS, I can use the NVIDIA logo in that blogpost without asking for NVIDIA's permission because I'm using it in an informational/editorial context.

**Comment by mrocklin** [comment]
Ooh...  I really like the styling here:  

Including a screenshot for others

Screen Shot 2019-05-18 at 1 07 30 PM

**Comment by mrocklin** [comment]
A few more to add to the list (though I can also find some time to add these to HTML directly if desired):

-  Scikit-Learn (through Joblib)
-  MDAnalysis https://www.mdanalysis.org/
-  XGBoost (maybe soon?) https://github.com/dmlc/xgboost/pull/4473/
-  TPot
-  Iris: https://scitools.org.uk/iris/docs/latest/

**Comment by mrocklin** [comment]
For the libraries without a logo (satpy, streamz, ...) maybe we include them in the grid anyway, but just with a blank space where the logo would go?

**Comment by jrbourbeau** [comment]
> Ooh... I really like the styling here

Thanks, but I can't take credit for it. Fringe benefit of being married to a web developer : ) 

I'll add those additional projects to the list. And your suggestion for libraries without logos seems reasonable, we can try it out and see what it looks like

**Comment by mrocklin** [comment]
> Thanks, but I can't take credit for it. Fringe benefit of being married to a web developer : )

Watch out, admitting that publicly is dangerous :)  You two might be more popular than you want if people find out :)

**Comment by jrbourbeau** [comment]
Added the other projects you listed @mrocklin (except xgboost, which could be added when that PR is merged). I like the look of including projects without a logo in the the same grid layout as those that do, good suggestion! 


Screen Shot 2019-05-20 at 6 29 56 PM

**Comment by jrbourbeau** [comment]
Currently, we have our sponsors listed on both the landing page (`index.html`) and the "Who uses Dask?" page (`users.html`). I'm slightly inclined to either remove sponsors from the "Who uses Dask?" page, or move that section towards the bottom of the page.

**Comment by mrocklin** [comment]
> Currently, we have our sponsors listed on both the landing page (index.html) and the "Who uses Dask?" page (users.html). I'm slightly inclined to either remove sponsors from the "Who uses Dask?" page, or move that section towards the bottom of the page.

Sounds good to me.  We could also merge this page onto the main page, and add the "Powered By Dask" section just below.

**Comment by jrbourbeau** [comment]
Thanks for the suggestions @mrocklin, I moved the "Powered by Dask" section to the main page. Any other edits / features we'd like to include in this PR? 

I'm happy to merge this in as is, but am also totally fine continuing to add nice things to the website : )

**Comment by TomAugspurger** [comment]
👍, I think this looks nice.

**Comment by mrocklin** [comment]
Thanks for doing this @jrbourbeau .  Let's merge!

**Comment by stefanv** [comment]
The new section looks great.  We also use Dask as the job engine underneath http://cesium-ml.org/ and https://skyportal.io/ (via https://github.com/cesium-ml/baselayer).

**Comment by mrocklin** [comment]
Would you be interested in adding your project to this list?

**Comment by TomAugspurger** [comment]
Done in https://github.com/dask/dask.github.io/pull/9 :)

**Pull request merged**
